### ISSUE TITLE
Custom CSS file doesn't work anymore?

### ISSUE THREAD

**Issue by lefoy** [wesbos/aprilFools.css#26]
I tried to add some CSS inside `~/Library/Application Support/Google/Chrome/Default/User StyleSheets/Custom.css` but nothing happen. I tried to close/reopen Chrome but still nothing.
Does this still work?

Thanks for your help :)

**Comment by lefoy** [comment]
Oh well it seems that user stylesheets has been removed from Chrome :(
https://codereview.chromium.org/66383005/

**Comment by wesbos** [comment]
RIP custom.css
